package cbopenif

FunctionBlockType :: distinct rawptr

FunctionBlockTypeIF :: struct #raw_union {
    #subtype iunknownif: IUnknownIF,
    using vtable: ^FunctionBlockTypeVTable,
}

FunctionBlockTypeVTable :: struct {
    using iunknownvtable: IUnknownVTable,
    NameGet:                      proc "system" (this: ^FunctionBlockTypeIF, name: ^BStr) -> HResult,
    NamePut:                      proc "system" (this: ^FunctionBlockTypeIF, name: BStr) -> HResult,
    ProtectedGet:                 proc "system" (this: ^FunctionBlockTypeIF, Protected: ^VariantBool) -> HResult,
    ProtectedPut:                 proc "system" (this: ^FunctionBlockTypeIF, Protected: VariantBool) -> HResult,
    HiddenGet:                    proc "system" (this: ^FunctionBlockTypeIF, Hidden: ^VariantBool) -> HResult,
    HiddenPut:                    proc "system" (this: ^FunctionBlockTypeIF, Hidden: VariantBool) -> HResult,
    ScopeGet:                     proc "system" (this: ^FunctionBlockTypeIF, Scope: ^ScopeType) -> HResult,
    ScopePut:                     proc "system" (this: ^FunctionBlockTypeIF, Scope: ScopeType) -> HResult,
    InteractionWindowGet:         proc "system" (this: ^FunctionBlockTypeIF, InteractionWindow: ^BStr) -> HResult,
    InteractionWindowPut:         proc "system" (this: ^FunctionBlockTypeIF, InteractionWindow: BStr) -> HResult,
    AlarmOwnerGet:                proc "system" (this: ^FunctionBlockTypeIF, AlarmOwner: ^VariantBool) -> HResult,
    AlarmOwnerPut:                proc "system" (this: ^FunctionBlockTypeIF, AlarmOwner: VariantBool) -> HResult,
    GuidGet:                      proc "system" (this: ^FunctionBlockTypeIF, Guid: ^BStr) -> HResult,
    GuidPut:                      proc "system" (this: ^FunctionBlockTypeIF, Guid: BStr) -> HResult,
    SILLevelGet:                  proc "system" (this: ^FunctionBlockTypeIF, SILLevel: ^BStr) -> HResult,
    SILLevelPut:                  proc "system" (this: ^FunctionBlockTypeIF, SILLevel: BStr) -> HResult,
    SimulationMarkGet:            proc "system" (this: ^FunctionBlockTypeIF, SimulationMark: ^VariantBool) -> HResult,
    SimulationMarkPut:            proc "system" (this: ^FunctionBlockTypeIF, SimulationMark: VariantBool) -> HResult,
    ReservedByFunctionGet:        proc "system" (this: ^FunctionBlockTypeIF, ReservedByFunction: ^BStr) -> HResult,
    ReservedByFunctionPut:        proc "system" (this: ^FunctionBlockTypeIF, ReservedByFunction: BStr) -> HResult,
    DescriptionGet:               proc "system" (this: ^FunctionBlockTypeIF, Description: ^BStr) -> HResult,
    DescriptionPut:               proc "system" (this: ^FunctionBlockTypeIF, Description: BStr) -> HResult,
    ParametersGet:                proc "system" (this: ^FunctionBlockTypeIF, Parameters: ^rawptr) -> HResult,
    Missing30:                    proc "system" (this: ^FunctionBlockTypeIF) -> HResult,
    ParametersPut:                proc "system" (this: ^FunctionBlockTypeIF, Parameters: rawptr) -> HResult,
    ExtensibleParametersGet:      proc "system" (this: ^FunctionBlockTypeIF, ExtensibleParameters: ^rawptr) -> HResult,
    Missing33:                    proc "system" (this: ^FunctionBlockTypeIF) -> HResult,
    ExtensibleParametersPut:      proc "system" (this: ^FunctionBlockTypeIF, ExtensibleParameters: rawptr) -> HResult,
    VariablesGet:                 proc "system" (this: ^FunctionBlockTypeIF, Variables: ^rawptr) -> HResult,
    Missing36:                    proc "system" (this: ^FunctionBlockTypeIF) -> HResult,
    VariablesPut:                 proc "system" (this: ^FunctionBlockTypeIF, Variables: rawptr) -> HResult,
    ExternalVariablesGet:         proc "system" (this: ^FunctionBlockTypeIF, ExternalVariables: ^rawptr) -> HResult,
    Missing39:                    proc "system" (this: ^FunctionBlockTypeIF) -> HResult,
    ExternalVariablesPut:         proc "system" (this: ^FunctionBlockTypeIF, ExternalVariables: rawptr) -> HResult,
    FunctionBlocksGet:            proc "system" (this: ^FunctionBlockTypeIF, FunctionBlocks: ^rawptr) -> HResult,
    Missing42:                    proc "system" (this: ^FunctionBlockTypeIF) -> HResult,
    FunctionBlocksPut:            proc "system" (this: ^FunctionBlockTypeIF, FunctionBlocks: rawptr) -> HResult,
    ControModulesGet:             proc "system" (this: ^FunctionBlockTypeIF, ControModules: ^rawptr) -> HResult,
    Missing45:                    proc "system" (this: ^FunctionBlockTypeIF) -> HResult,
    ControModulesPut:             proc "system" (this: ^FunctionBlockTypeIF, ControModules: rawptr) -> HResult,
    CodeBlocksGet:                proc "system" (this: ^FunctionBlockTypeIF, CodeBlocks: ^rawptr) -> HResult,
    Missing48:                    proc "system" (this: ^FunctionBlockTypeIF) -> HResult,
    CodeBlocksPut:                proc "system" (this: ^FunctionBlockTypeIF, CodeBlocks: rawptr) -> HResult,
    Serialize:                    proc "system" (this: ^FunctionBlockTypeIF, XML: ^BStr) -> HResult,
    InstantiateAsAspectObjectGet: proc "system" (this: ^FunctionBlockTypeIF, InstantiateAsAspectObject: ^VariantBool) -> HResult,
    InstantiateAsAspectObjectPut: proc "system" (this: ^FunctionBlockTypeIF, InstantiateAsAspectObject: VariantBool) -> HResult,
    EmbeddedGraphicsVisibleGet:   proc "system" (this: ^FunctionBlockTypeIF, EmbeddedGraphicsVisible: ^VariantBool) -> HResult,
    EmbeddedGraphicsVisiblePut:   proc "system" (this: ^FunctionBlockTypeIF, EmbeddedGraphicsVisible: VariantBool) -> HResult,
    RestrictedSILGet:             proc "system" (this: ^FunctionBlockTypeIF, RestrictedSIL: ^VariantBool) -> HResult,
    RestrictedSILPut:             proc "system" (this: ^FunctionBlockTypeIF, RestrictedSIL: VariantBool) -> HResult,
}

