package cbopen

import "../com"

@(private="file") BStr        :: com.BStr
@(private="file") GUID        :: com.GUID
@(private="file") HResult     :: com.HResult
@(private="file") Variant     :: com.Variant
@(private="file") VariantBool :: com.VariantBool

CBOpenIFErrorCodes :: enum u32 {
    NotSupported     = 0x80040bc2,
    Mode             = 0x80040bc3,
    Xml              = 0x80040bc4,
    Name             = 0x80040bc5,
    Path             = 0x80040bc6,
    CreatedDirectory = 0x80040bc7,
    AlreadyExists    = 0x80040bc8,
    MaxExceeded      = 0x80040bc9,
    Open             = 0x80040bca,
    Save             = 0x80040bcb,
    DoesNotExist     = 0x80040bcc,
    Delete           = 0x80040bcd,
    Type             = 0x80040bce,
    State            = 0x80040bcf,
    Version          = 0x80040bd0,
    ModalDialog      = 0x80040bd1,
    NameConflict     = 0x80040bd2,
    GUID             = 0x80040bd3,
    Decryption       = 0x80040bd4,
    Checksum         = 0x80040bd5,
    ChecksumCodePage = 0x80040bd6,
    InUse            = 0x80040bd7,
    Reservation      = 0x80040bd8
}

CBOpenIF :: struct #raw_union {
    #subtype iunknownif: com.IUnknownIF,
    using vtable: ^CBOpenVTable,
}

cbopenif: ^CBOpenIF

CBOpenVTable :: struct {
    using iunknownvtable: com.IUnknownVTable,
    NewProject:                          proc "system" (this: ^CBOpenIF, ProjectName, DirectoryPath, GUID, TemplateName: BStr) -> HResult,
    OpenProject:                         proc "system" (this: ^CBOpenIF, FilePath: BStr) -> HResult,
    CloseProject:                        proc "system" (this: ^CBOpenIF) -> HResult,
    GetProjectConstants:                 proc "system" (this: ^CBOpenIF, Constants: ^BStr) -> HResult,
    SetProjectConstants:                 proc "system" (this: ^CBOpenIF, Constants: BStr, Messages: ^BStr) -> HResult,
    NewLibrary:                          proc "system" (this: ^CBOpenIF, LibraryName, DirectoryPath, GUID: BStr) -> HResult,
    InsertLibrary:                       proc "system" (this: ^CBOpenIF, FilePath: BStr) -> HResult,
    RenameLibrary:                       proc "system" (this: ^CBOpenIF, LibraryName, NewLibraryName: BStr) -> HResult,
    DeleteLibrary:                       proc "system" (this: ^CBOpenIF, LibraryName: BStr) -> HResult,
    GetLibraryProjectConstants:          proc "system" (this: ^CBOpenIF, LibraryName: BStr, Constants: ^BStr) -> HResult,
    SetLibraryProjectConstants:          proc "system" (this: ^CBOpenIF, LibraryName, Constants: BStr, Messages: ^BStr) -> HResult,
    NewApplication:                      proc "system" (this: ^CBOpenIF, ApplicationName, DirectoryPath, GUID, TemplateName: BStr) -> HResult,
    InsertApplication:                   proc "system" (this: ^CBOpenIF, FilePath: BStr) -> HResult,
    RenameApplication:                   proc "system" (this: ^CBOpenIF, ApplicationName, NewApplicationName: BStr) -> HResult,
    DeleteApplication:                   proc "system" (this: ^CBOpenIF, ApplicationName: BStr) -> HResult,
    GetApplicationVariables:             proc "system" (this: ^CBOpenIF, ApplicationName: BStr, Variables: ^BStr) -> HResult,
    SetApplicationVariables:             proc "system" (this: ^CBOpenIF, ApplicationName, Variables: BStr, Messages: ^BStr) -> HResult,
    GetTaskConnection:                   proc "system" (this: ^CBOpenIF, ObjectPath: BStr, TaskConnection: ^BStr) -> HResult,
    SetTaskConnection:                   proc "system" (this: ^CBOpenIF, ObjectPath, TaskConnection: BStr) -> HResult,
    NewController:                       proc "system" (this: ^CBOpenIF, ControllerName, ControllerType, DirectoryPath, GUID, TemplateName: BStr) -> HResult,
    InsertController:                    proc "system" (this: ^CBOpenIF, FilePath: BStr) -> HResult,
    RenameController:                    proc "system" (this: ^CBOpenIF, ControllerName, NewControllerName: BStr) -> HResult,
    DeleteController:                    proc "system" (this: ^CBOpenIF, ControllerName: BStr) -> HResult,
    GetSystemIdentity:                   proc "system" (this: ^CBOpenIF, ControllerName: BStr, SystemIdentity: ^BStr) -> HResult,
    SetSystemIdentity:                   proc "system" (this: ^CBOpenIF, ControllerName, SystemIdentity: BStr) -> HResult,
    NewDataType:                         proc "system" (this: ^CBOpenIF, DataTypeName, AppOrLibraryName, DataTypeContent: BStr, Messages: ^BStr) -> HResult,
    GetDataType:                         proc "system" (this: ^CBOpenIF, DataTypePath: BStr, DataTypeContent: ^BStr) -> HResult,
    SetDataType:                         proc "system" (this: ^CBOpenIF, DataTypePath, DataTypeContent: BStr, Messages: ^BStr) -> HResult,
    DeleteDataType:                      proc "system" (this: ^CBOpenIF, DataTypePath: BStr) -> HResult,
    NewFunctionBlockType:                proc "system" (this: ^CBOpenIF, FunctionBlockTypeName, AppOrLibraryName, FunctionBlockTypeContent: BStr, Messages: ^BStr) -> HResult,
    GetFunctionBlockType:                proc "system" (this: ^CBOpenIF, FunctionBlockTypePath: BStr, Content: ^BStr) -> HResult,
    SetFunctionBlockType:                proc "system" (this: ^CBOpenIF, FunctionBlockTypePath, FunctionBlockTypeContent: BStr, Messages: ^BStr) -> HResult,
    DeleteFunctionBlockType:             proc "system" (this: ^CBOpenIF, FunctionBlockTypePath: BStr) -> HResult,
    NewControlModuleType:                proc "system" (this: ^CBOpenIF, ControlModuelTypeName, AppOrLibraryName, ControlModuelTypeContent: BStr, Messages: ^BStr) -> HResult,
    GetControlModuleType:                proc "system" (this: ^CBOpenIF, ControlModuelTypePath: BStr, ControlModuelTypeContent: ^BStr) -> HResult,
    SetControlModuleType:                proc "system" (this: ^CBOpenIF, ControlModuelTypePath, ControlModuelTypeContent: BStr, Messages: ^BStr) -> HResult,
    DeleteControlModuleType:             proc "system" (this: ^CBOpenIF, ControlModuelTypePath: BStr) -> HResult,
    NewControlModule:                    proc "system" (this: ^CBOpenIF, ControlModuleName, ControlModuleType, PathToParent, ControlModuleContent: BStr, Messages: ^BStr) -> HResult,
    NewSingleControlModule:              proc "system" (this: ^CBOpenIF, ControlModuleName, PathToParent, ControlModuleContent: BStr, Messages: ^BStr) -> HResult,
    GetControlModule:                    proc "system" (this: ^CBOpenIF, ControlModulePath: BStr, ControlModuleContent: ^BStr) -> HResult,
    SetControlModule:                    proc "system" (this: ^CBOpenIF, ControlModulePath, ControlModuleContent: BStr, Messages: ^BStr) -> HResult,
    DeleteControlModule:                 proc "system" (this: ^CBOpenIF, ControlModulePath: BStr) -> HResult,
    NewProgram:                          proc "system" (this: ^CBOpenIF, ProgramName, ApplicationName, ProgramContent: BStr, Messages: ^BStr) -> HResult,
    GetProgram:                          proc "system" (this: ^CBOpenIF, ProgramPath: BStr, ProgramContent: ^BStr) -> HResult,
    SetProgram:                          proc "system" (this: ^CBOpenIF, ProgramPath, ProgramContent: BStr, Messages: ^BStr) -> HResult,
    DeleteProgram:                       proc "system" (this: ^CBOpenIF, ProgramPath: BStr) -> HResult,
    GetAccessVariables:                  proc "system" (this: ^CBOpenIF, ControllerName: BStr, AccessVariableContent: ^BStr) -> HResult,
    SetAccessVariables:                  proc "system" (this: ^CBOpenIF, ControllerName, AccessVariableContent: BStr, Messages: ^BStr) -> HResult,
    NewTask:                             proc "system" (this: ^CBOpenIF, TaskName, ControllerName, TaskContent: BStr) -> HResult,
    GetTask:                             proc "system" (this: ^CBOpenIF, TaskPath: BStr, TaskContent: ^BStr) -> HResult,
    SetTask:                             proc "system" (this: ^CBOpenIF, TaskPath, TaskContent: BStr) -> HResult,
    DeleteTask:                          proc "system" (this: ^CBOpenIF, TaskPath: BStr) -> HResult,
    GetConnectedApplications:            proc "system" (this: ^CBOpenIF, ControllerName: BStr, ConnectedApplicationsContent: ^BStr) -> HResult,
    SetConnectedApplications:            proc "system" (this: ^CBOpenIF, ControllerName, ConnectedApplicationsContent: BStr, Messages: ^BStr) -> HResult,
    Online:                              proc "system" (this: ^CBOpenIF, IsOnline: ^VariantBool, Messages: ^BStr) -> HResult,
    DownloadAndGoOnline:                 proc "system" (this: ^CBOpenIF, IsOnline: ^VariantBool, Messages: ^BStr) -> HResult,
    TestMode:                            proc "system" (this: ^CBOpenIF, IsTestMode: ^VariantBool, Messages: ^BStr) -> HResult,
    Offline:                             proc "system" (this: ^CBOpenIF, Messages: ^BStr) -> HResult,
    NewHardwareUnit:                     proc "system" (this: ^CBOpenIF, HwPath: BStr, HwTypeID: Variant, HwQualifier, HwUnitContent, RedundantTo: BStr, Messages: ^BStr) -> HResult,
    GetHardwareUnit:                     proc "system" (this: ^CBOpenIF, HwPath: BStr, IncludeSubUnits: VariantBool, HwUnitContent: ^BStr) -> HResult,
    GetHardwareType:                     proc "system" (this: ^CBOpenIF, HarwareLibraryName, HarwareLibraryTypeNmae: BStr, HarwareTypeContent: ^BStr) -> HResult,
    SetHardwareUnit:                     proc "system" (this: ^CBOpenIF, HwPath, HwUnitContent: BStr, Messages: ^BStr) -> HResult,
    DeleteHardwareUnit:                  proc "system" (this: ^CBOpenIF, HwPath: BStr, RemoveRedundantOnly: VariantBool) -> HResult,
    MoveHardwareUnitTo:                  proc "system" (this: ^CBOpenIF, HwPath, NewHwPath: BStr, DoSwap: VariantBool) -> HResult,
    GetProjectTree:                      proc "system" (this: ^CBOpenIF, Path: BStr, Depth: i32, IncludeRuntimeInstances: VariantBool, ProjectTreeContent: ^BStr) -> HResult,
    NewFunctionBlock:                    proc "system" (this: ^CBOpenIF, FunctionBlockName, FunctionBlockType, PathToParent, FunctionBlockContent: BStr, Messages: ^BStr) -> HResult,
    GetFunctionBlock:                    proc "system" (this: ^CBOpenIF, FunctionBlockPath: BStr, FunctionBlockContent: ^BStr) -> HResult,
    SetFunctionBlock:                    proc "system" (this: ^CBOpenIF, FunctionBlockPath, FunctionBlockContent: BStr, Messages: ^BStr) -> HResult,
    DeleteFunctionBlock:                 proc "system" (this: ^CBOpenIF, FunctionBlockPath: BStr) -> HResult,
    Reserve:                             proc "system" (this: ^CBOpenIF, FOUName: BStr) -> HResult,
    IsReservedBy:                        proc "system" (this: ^CBOpenIF, FOUName: BStr, Reserver: ^BStr) -> HResult,
    ReleaseReservation:                  proc "system" (this: ^CBOpenIF, FOUName: BStr) -> HResult,
    GetSetting:                          proc "system" (this: ^CBOpenIF, SettingName: BStr, Value: ^Variant) -> HResult,
    SetSetting:                          proc "system" (this: ^CBOpenIF, SettingName: BStr, Value: Variant) -> HResult,
    GetApplicationControlModules:        proc "system" (this: ^CBOpenIF, ApplicationName: BStr, ApplicationControlModulesContent: ^BStr) -> HResult,
    SetApplicationControlModules:        proc "system" (this: ^CBOpenIF, ApplicationName, ApplicationControlModulesContent: BStr, Messages: ^BStr) -> HResult,
    NewParameter:                        proc "system" (this: ^CBOpenIF, CBOpenIFParameterType: i32, ParameterName, DataType, PathToParent, ParameterContent: BStr, Messages: ^BStr) -> HResult,
    GetParameter:                        proc "system" (this: ^CBOpenIF, CBOpenIFParameterType: i32, ParameterPath: BStr, ParameterContent: ^BStr) -> HResult,
    SetParameter:                        proc "system" (this: ^CBOpenIF, CBOpenIFParameterType: i32, ParameterPath, ParameterContent: BStr, Messages: ^BStr) -> HResult,
    DeleteParameter:                     proc "system" (this: ^CBOpenIF, CBOpenIFParameterType: i32, ParameterPath: BStr) -> HResult,
    NewVariable:                         proc "system" (this: ^CBOpenIF, CBOpenIFVariableType: i32, VariableName, DataType, PathToParent, VariableContent: BStr, Messages: ^BStr) -> HResult,
    GetVariable:                         proc "system" (this: ^CBOpenIF, CBOpenIFVariableType: i32, VariablePath: BStr, VariableContent: ^BStr) -> HResult,
    SetVariable:                         proc "system" (this: ^CBOpenIF, CBOpenIFVariableType: i32, VariablePath, VariableContent: BStr, Messages: ^BStr) -> HResult,
    DeleteVariable:                      proc "system" (this: ^CBOpenIF, CBOpenIFVariableType: i32, VariablePath: BStr) -> HResult,
    GetCMConnection:                     proc "system" (this: ^CBOpenIF, ConnectionPath: BStr, ConnectionContent: ^BStr) -> HResult,
    SetCMConnection:                     proc "system" (this: ^CBOpenIF, ConnectionPath, ConnectionContent: BStr, Messages: ^BStr) -> HResult,
    NewCodeBlock:                        proc "system" (this: ^CBOpenIF, CBOpenIFCodeBlockType: i32, CodeBlockName, PathToParent, CodeBlockContent: BStr, Messages: ^BStr) -> HResult,
    GetCodeBlock:                        proc "system" (this: ^CBOpenIF, CodeBlockPath: BStr, CodeBlockContent: ^BStr) -> HResult,
    SetCodeBlock:                        proc "system" (this: ^CBOpenIF, CodeBlockPath, CodeBlockContent: BStr, Messages: ^BStr) -> HResult,
    DeleteCodeBlock:                     proc "system" (this: ^CBOpenIF, CodeBlockPath: BStr) -> HResult,
    GetOneInstanceInitVals:              proc "system" (this: ^CBOpenIF, InstacePath: BStr, InitValsContent: ^BStr) -> HResult,
    GetAllInstancesInitVals:             proc "system" (this: ^CBOpenIF, PathToParent: BStr, InitValsContent: ^BStr) -> HResult,
    SetOneInstanceInitVals:              proc "system" (this: ^CBOpenIF, InstancePath, InitValsContent: BStr, Messages: ^BStr) -> HResult,
    SetAllInstancesInitVals:             proc "system" (this: ^CBOpenIF, PathToParent, InitValsContent: BStr, Messages: ^BStr) -> HResult,
    DeleteOneInstanceInitVals:           proc "system" (this: ^CBOpenIF, InstancePath: BStr) -> HResult,
    DeleteAllInstancesInitVals:          proc "system" (this: ^CBOpenIF, PathToParent: BStr) -> HResult,
    RenameInstanceDataPath:              proc "system" (this: ^CBOpenIF, InstancePath, NewInstancePath: BStr) -> HResult,
    RenameDataType:                      proc "system" (this: ^CBOpenIF, DataTypePath, NewDataTypeName: BStr) -> HResult,
    RenameFunctionBlockType:             proc "system" (this: ^CBOpenIF, FunctionBlockTypePath, NewFunctionBlockTypeName: BStr) -> HResult,
    RenameControlModuleType:             proc "system" (this: ^CBOpenIF, ControlModuleTypePath, NewControlModuleTypeName: BStr) -> HResult,
    GetSingleControlModule:              proc "system" (this: ^CBOpenIF, SingleControlModulePath: BStr, SingleControlModuleContent: ^BStr) -> HResult,
    SetSingleControlModule:              proc "system" (this: ^CBOpenIF, SingleControlModulePath, SingleControlModuleContent: BStr, Messages: ^BStr) -> HResult,
    DeleteSingleControlModule:           proc "system" (this: ^CBOpenIF, SingleControlModulePath: BStr) -> HResult,
    GetConnectedLibraries:               proc "system" (this: ^CBOpenIF, AppOrLibraryName: BStr, ConnectedLibrariesContent: ^BStr) -> HResult,
    SetConnectedLibraries:               proc "system" (this: ^CBOpenIF, AppOrLibraryName, ConnectedLibrariesContent: BStr, Messages: ^BStr) -> HResult,
    SetLibraryVersion:                   proc "system" (this: ^CBOpenIF, LibraryName: BStr, MajorVersion, MinorVersion, Revision: i32) -> HResult,
    SetApplicationVersion:               proc "system" (this: ^CBOpenIF, ApplicationName: BStr, MajorVersion, MinorVersion, Revision: i32) -> HResult,
    SetControllerVersion:                proc "system" (this: ^CBOpenIF, ControllerName: BStr, MajorVersion, MinorVersion, Revision: i32) -> HResult,
    GetLibraryState:                     proc "system" (this: ^CBOpenIF, LibraryName: BStr, libraryState: ^BStr) -> HResult,
    SetLibraryState:                     proc "system" (this: ^CBOpenIF, LibraryName, libraryState: BStr) -> HResult,
    ConnectLibrary:                      proc "system" (this: ^CBOpenIF, AppOrLibraryName, LibraryName: BStr) -> HResult,
    DisconnectLibrary:                   proc "system" (this: ^CBOpenIF, AppOrLibraryName, LibraryName: BStr) -> HResult,
    GetControllerProperties:             proc "system" (this: ^CBOpenIF, ControllerName: BStr, PropertiesContent: ^BStr) -> HResult,
    SetControllerProperties:             proc "system" (this: ^CBOpenIF, ControllerName, PropertiesContent: BStr) -> HResult,
    GetTypePathFromGUID:                 proc "system" (this: ^CBOpenIF, AppOrLibraryName, GUID: BStr, TypePath: ^BStr) -> HResult,
    RenameProgram:                       proc "system" (this: ^CBOpenIF, ProgramPath, NewProgramName: BStr) -> HResult,
    RenameFunctionBlock:                 proc "system" (this: ^CBOpenIF, FunctionBlockPath, NewFunctionBlockName: BStr) -> HResult,
    RenameControlModule:                 proc "system" (this: ^CBOpenIF, ControlModulePath, NewControlModuleName: BStr) -> HResult,
    RenameTask:                          proc "system" (this: ^CBOpenIF, TaskPath, NewTaskName: BStr) -> HResult,
    RefreshProject:                      proc "system" (this: ^CBOpenIF) -> HResult,
    RefreshLibrary:                      proc "system" (this: ^CBOpenIF, LibraryName: BStr) -> HResult,
    RefreshApplication:                  proc "system" (this: ^CBOpenIF, ApplicationName: BStr) -> HResult,
    RefreshController:                   proc "system" (this: ^CBOpenIF, ControllerName: BStr) -> HResult,
    ReplaceHardwareUnitType:             proc "system" (this: ^CBOpenIF, HwPath: BStr, HwTypeId: Variant, HwQualifier: BStr) -> HResult,
    GetValidHardwarePositions:           proc "system" (this: ^CBOpenIF, HwFatherPath: BStr, HwTypeId: Variant, HwQualifier: BStr, Positions: ^BStr) -> HResult,
    InsertDataType:                      proc "system" (this: ^CBOpenIF, DataTypeName, AppOrLibraryName, GUID: BStr) -> HResult,
    InsertFunctionBlockType:             proc "system" (this: ^CBOpenIF, FunctionBlockName, AppOrLibraryName, GUID: BStr) -> HResult,
    InsertControlModuleType:             proc "system" (this: ^CBOpenIF, ControlModuleTypeName, AppOrLibraryName, GUID: BStr) -> HResult,
    InsertProgram:                       proc "system" (this: ^CBOpenIF, ProgramName, ApplicationName, GUID: BStr) -> HResult,
    InsertSingleControlModule:           proc "system" (this: ^CBOpenIF, ModuleName, PathToParent, GUID: BStr) -> HResult,
    GetApplicationProperties:            proc "system" (this: ^CBOpenIF, ApplicationName: BStr, PropertiesContent: ^BStr) -> HResult,
    SetApplicationProperties:            proc "system" (this: ^CBOpenIF, ApplicationName, PropertiesContent: BStr) -> HResult,
    NewHardwareLibrary:                  proc "system" (this: ^CBOpenIF, HardwareLibraryName, DirectoryPath, GUID: BStr) -> HResult,
    InsertHardwareLibrary:               proc "system" (this: ^CBOpenIF, FilePath: BStr) -> HResult,
    DeleteHardwareLibrary:               proc "system" (this: ^CBOpenIF, HardwareLibraryName: BStr) -> HResult,
    ConnectHardwareLibrary:              proc "system" (this: ^CBOpenIF, ControllerName, HardwareLibrary: BStr) -> HResult,
    DisconnectHardwareLibrary:           proc "system" (this: ^CBOpenIF, ControllerName, HardwareLibrary: BStr) -> HResult,
    GetHardwareLibraryState:             proc "system" (this: ^CBOpenIF, HardwareLibraryName: BStr, LibraryState: ^BStr) -> HResult,
    SetHardwareLibraryState:             proc "system" (this: ^CBOpenIF, HardwareLibraryName, state: BStr) -> HResult,
    SetHardwareLibraryVersion:           proc "system" (this: ^CBOpenIF, HardwareLibraryName: BStr, MajorVersion, MinorVersion, Revision: i32) -> HResult,
    CopyHardwareType:                    proc "system" (this: ^CBOpenIF, SourceHardwareLibraryName, SourceHardwareTypeGUID, DestinationHardwareLibraryName, DestinationHardwareTypeGUID: BStr) -> HResult,
    DeleteHardwareType:                  proc "system" (this: ^CBOpenIF, HardwareLibraryName, Type_Name: BStr) -> HResult,
    GetConnectedHardwareLibraries:       proc "system" (this: ^CBOpenIF, ControllerName: BStr, ConnectedHardwareLibrariesContent: ^BStr) -> HResult,
    SetConnectedHardwareLibraries:       proc "system" (this: ^CBOpenIF, ControllerName, ConnectedHardwareLibrariesContent: BStr, Messages: ^BStr) -> HResult,
    CopyHardwareLibrary:                 proc "system" (this: ^CBOpenIF, SourceHardwareLibraryName, DestinationHardwareLibraryName, DestinationHardwareLibraryGUID: BStr) -> HResult,
    RefreshHardwareLibrary:              proc "system" (this: ^CBOpenIF, Name: BStr) -> HResult,
    ReplaceConnectedHardwareLibrary:     proc "system" (this: ^CBOpenIF, ControllerName, ConnectedHardwareLibraryName, replacingHardwareLibraryName: BStr) -> HResult,
    AddHardwareTypeFile:                 proc "system" (this: ^CBOpenIF, HardwareLibraryName, hardwareTypeGUID: BStr, FileType: i32, FilePath, Version, BuildVersion, BuildDate, FwName: BStr) -> HResult,
    InsertHardwareType:                  proc "system" (this: ^CBOpenIF, HardwareTypeName, HardwareLibraryName, HardwareTypeGUID, HardwareTypeID: BStr) -> HResult,
    ReplaceConnectedLibrary:             proc "system" (this: ^CBOpenIF, AppOrLibraryName, ConnectedLibraryName, ReplacingLibraryName: BStr) -> HResult,
    NewProjectInEnvironment:             proc "system" (this: ^CBOpenIF, ProjectName, GUID, RemplateName, EnvironmentGUIDOrName: BStr) -> HResult,
    OpenProjectInEnvironment:            proc "system" (this: ^CBOpenIF, ProjectGUIDOrName, EnvironmentGUIDOrName: BStr) -> HResult,
    RenameHardwareLibrary:               proc "system" (this: ^CBOpenIF, HardwareLibraryName, NewHardwareLibraryName: BStr) -> HResult,
    GetProjectAndEnvironmentInformation: proc "system" (this: ^CBOpenIF, ProjectName, ProjectGUID, EnvironmentName, EnvironmentGUID: ^BStr) -> HResult,
    SetStorage:                          proc "system" (this: ^CBOpenIF, pIAcStorage: rawptr) -> HResult,
    WriteInformation:                    proc "system" (this: ^CBOpenIF, Message: BStr) -> HResult,
    WriteWarning:                        proc "system" (this: ^CBOpenIF, Message: BStr) -> HResult,
    WriteError:                          proc "system" (this: ^CBOpenIF, Message: BStr) -> HResult,
    NewFolder:                           proc "system" (this: ^CBOpenIF, CBOpenIFFolderType: i32, FolderName, PathToParentFolder, GUID: BStr) -> HResult,
    RenameFolder:                        proc "system" (this: ^CBOpenIF, CBOpenIFFolderType: i32, FolderPath, NewFolderName: BStr) -> HResult,
    DeleteFolder:                        proc "system" (this: ^CBOpenIF, CBOpenIFFolderType: i32, FolderPath: BStr) -> HResult,
    MoveFolder:                          proc "system" (this: ^CBOpenIF, CBOpenIFFolderType: i32, FolderPath, DestinationFolderPath: BStr) -> HResult,
    MoveFolderObject:                    proc "system" (this: ^CBOpenIF, CBOpenIFFolderType: i32, ObjectName, DestinationFolderPath: BStr) -> HResult,
    NewDiagram:                          proc "system" (this: ^CBOpenIF, DiagramName, ApplicationName, DiagramContent: BStr, Messages: ^BStr) -> HResult,
    GetDiagram:                          proc "system" (this: ^CBOpenIF, DiagramPath: BStr, DiagramContent: ^BStr) -> HResult,
    SetDiagram:                          proc "system" (this: ^CBOpenIF, DiagramPath, DiagramContent: BStr, Messages: ^BStr) -> HResult,
    DeleteDiagram:                       proc "system" (this: ^CBOpenIF, DiagramPath: BStr) -> HResult,
    RenameDiagram:                       proc "system" (this: ^CBOpenIF, DiagramPath, newDiagramName: BStr) -> HResult,
    InsertDiagram:                       proc "system" (this: ^CBOpenIF, DiagramName, ApplicationName, GUID: BStr) -> HResult,
    InsertHardwareDefinitionFile:        proc "system" (this: ^CBOpenIF, HardwareLibraryName, FilePath: BStr, fileAdded: ^VariantBool, Messages: ^BStr) -> HResult,
    GetExecutionOrder:                   proc "system" (this: ^CBOpenIF, CBOpenIFExecutionInstanceType: i32, ApplicationName: BStr, ExecutionOrderContent: ^BStr) -> HResult,
    SetExecutionOrder:                   proc "system" (this: ^CBOpenIF, CBOpenIFExecutionInstanceType: i32, ApplicationName, ExecutionOrderContent: BStr, Messages: ^BStr) -> HResult,
    NewDiagramType:                      proc "system" (this: ^CBOpenIF, DiagramTypeName, AppOrLibraryName, Content: BStr, Messages: ^BStr) -> HResult,
    GetDiagramType:                      proc "system" (this: ^CBOpenIF, DiagramTypePath: BStr, DiagramTypeContent: ^BStr) -> HResult,
    SetDiagramType:                      proc "system" (this: ^CBOpenIF, DiagramTypePath, DiagramTypeContent: BStr, Messages: ^BStr) -> HResult,
    DeleteDiagramType:                   proc "system" (this: ^CBOpenIF, DiagramTypePath: BStr) -> HResult,
    RenameDiagramType:                   proc "system" (this: ^CBOpenIF, DiagramTypePath, NewDiagramTypeName: BStr) -> HResult,
    InsertDiagramType:                   proc "system" (this: ^CBOpenIF, DiagramTypeName, AppOrLibraryName, GUID: BStr) -> HResult,
    NewDiagramInstance:                  proc "system" (this: ^CBOpenIF, DiagramInstanceName, DiagramType, PathToParent, DiagramInstanceContent: BStr, Messages: ^BStr) -> HResult,
    GetDiagramInstance:                  proc "system" (this: ^CBOpenIF, DiagramInstancePath: BStr, DiagramInstanceContent: ^BStr) -> HResult,
    SetDiagramInstance:                  proc "system" (this: ^CBOpenIF, DiagramInstancePath, DiagramInstanceContent: BStr, Messages: ^BStr) -> HResult,
    DeleteDiagramInstance:               proc "system" (this: ^CBOpenIF, DiagramInstancePath: BStr) -> HResult,
    RenameDiagramInstance:               proc "system" (this: ^CBOpenIF, DiagramInstancePath, NewDiagramInstanceName: BStr) -> HResult,
    NewSignal:                           proc "system" (this: ^CBOpenIF, CBOpenIFSignalType: i32, SignalName, PathToParent, SignalContent: BStr, Messages: ^BStr) -> HResult,
    GetSignal:                           proc "system" (this: ^CBOpenIF, CBOpenIFSignalType: i32, SignalName, PathToParent: BStr, SignalContent: ^BStr) -> HResult,
    SetSignal:                           proc "system" (this: ^CBOpenIF, CBOpenIFSignalType: i32, SignalName, PathToParent, SignalContent: BStr, Messages: ^BStr) -> HResult,
    DeleteSignal:                        proc "system" (this: ^CBOpenIF, CBOpenIFSignalType: i32, SignalName, PathToParent: BStr) -> HResult,
    AddHardwareLibraryFile:              proc "system" (this: ^CBOpenIF, HardwareLibraryName: BStr, CBOpenIFHardwareLibraryFileType: i32, FilePath, Version: BStr) -> HResult,
    GetHardwareLibraryFiles:             proc "system" (this: ^CBOpenIF, HardwareLibraryName: BStr, HardwareLibraryFiles: ^BStr) -> HResult,
    DeleteHardwareLibraryFile:           proc "system" (this: ^CBOpenIF, HardwareLibraryName: BStr, CBOpenIFHardwareLibraryFileType: i32, FileName: BStr) -> HResult,
    SetHardwareType:                     proc "system" (this: ^CBOpenIF, HardwareLibraryName, HardwareTypeName, HardwareTypeNameContent: BStr, Messages: ^BStr) -> HResult,
    GetHardwareDefinitionInfo:           proc "system" (this: ^CBOpenIF, HardwareLibraryName, HardwareTypeName: BStr, HwdInfoContent: ^BStr) -> HResult,
    InsertHardwareUnit:                  proc "system" (this: ^CBOpenIF, ParentHwPath, GUID: BStr) -> HResult,
    GetControllerSettings:               proc "system" (this: ^CBOpenIF, ControllerName: BStr, ControllerSettings: ^BStr) -> HResult,
    SetControllerSettings:               proc "system" (this: ^CBOpenIF, ControllerName, ControllerSettings: BStr) -> HResult,
    GetFDConnection:                     proc "system" (this: ^CBOpenIF, ConnectionPath: BStr, ConnectionContent: ^BStr) -> HResult,
    SetFDConnection:                     proc "system" (this: ^CBOpenIF, ConnectionPath, ConnectionContent: BStr, Messages: ^BStr) -> HResult,
    ListAvailableLibraries:              proc "system" (this: ^CBOpenIF, Libraries: ^BStr) -> HResult,
    ListAvailableHardwareLibraries:      proc "system" (this: ^CBOpenIF, HardwareLibraries: ^BStr) -> HResult,
    LoopCheckDownloadAndGoOnline:        proc "system" (this: ^CBOpenIF, IsOnline: ^VariantBool, Messages: ^BStr) -> HResult,
}

connect :: proc() -> (ok: bool) {
    if cbopenif != nil do return
    
    ok = com.initialize()
    if !ok do return

    clsid := GUID{
        0x45902D56,
        0xD537,
        0x486C,
        {0x89, 0x1B, 0x81, 0x1C, 0xDA, 0x41, 0x0C, 0x77},
    }

    iid := GUID{
        0xEDF53D60,
        0xF499,
        0x4EDC,
        {0xAB, 0x7F, 0x10, 0x38, 0x95, 0xFE, 0x89, 0x91},
    }

    ok = com.create_instance(&clsid, &iid, cast(^rawptr)&cbopenif)
    if !ok {
        com.uninitialize()
        cbopenif = nil
        return
    }

    return true
}

disconnect :: proc() -> (ok: bool) {
    if cbopenif != nil {
        cbopenif->Release()
        cbopenif = nil
    }
    com.uninitialize()

    return true
}
